print("Hello world!")
print("Welcome to Git task")
print("Collab1: Update from collaborator")
print("Collab2: Update from Collaborator2")
print("-----------------------------")
print("Sum of Two number is 100")
