print("Hello world!")
print("Welcome to Git task")
print("Collab1: Update from collaborator")
print("Collab2: Update from Collaborator2")
print("-----------------------------")
print("a = 50")
print("b = 50")
print("Sum of Two number is 100")
